export const colors = {
  background: '#FFFFFF',
  backgroundAssistive: '#F8F8F8',
  backgroundNeutral: '#F2F2F3',
  border: '#E4E4E5',
  calendarSaturday: '#008BFF',
  calendarSunday: '#FF383C',
  danger: '#EE2B2B',
  dangerSoft: '#FFF0F0',
  disabled: '#D1D4D5',
  focus: '#FF4A75',
  info: '#168CFF',
  inputBackground: '#F8F8F8',
  onDisabled: '#767680',
  onPrimary: '#FFFFFF',
  primary: '#FF1956',
  // Figma `primary/assistive`. The opaque tint behind a coupon's ticket badge —
  // `primaryRange` is the same hue at 48% and reads noticeably lighter.
  primaryAssistive: '#FFC9D3',
  primaryPressed: '#E9164E',
  primaryRange: 'rgba(255, 201, 211, 0.48)',
  primarySelected: 'rgba(255, 25, 86, 0.08)',
  primarySoft: '#FFF0F4',
  success: '#1F9D55',
  successSoft: '#EAF8F0',
  surface: '#FFFFFF',
  surfaceMuted: '#F6F6F7',
  surfacePressed: '#EDEDEF',
  text: '#3B3B40',
  // Figma `label/alternative`. Sits between `text` and `textMuted`, for the
  // supporting lines a muted grey would push too far back (coupon validity dates,
  // notice copy).
  textAlternative: '#5E5E66',
  textDisabled: '#9C9CA3',
  textMuted: '#767680',
  textStrong: '#0C0C0D',
  warning: '#C77800',
  warningSoft: '#FFF5E5',
} as const;
